const models = [
  { name: "iPhone X" },
  { name: "iPhone XS" },
  { name: "iPhone XS Max" },
  { name: "iPhone XR" },
  { name: "iPhone 11" },
  { name: "iPhone 11 Pro" },
  { name: "iPhone 11 Pro Max" },
  { name: "iPhone 12" },
  { name: "iPhone 12 mini" },
  { name: "iPhone 12 Pro" },
  { name: "iPhone 12 Pro Max" },
  { name: "iPhone 13" },
  { name: "iPhone 13 mini" },
  { name: "iPhone 13 Pro" },
  { name: "iPhone 13 Pro Max" },
  { name: "iPhone 14" },
  { name: "iPhone 14 Plus" },
  { name: "iPhone 14 Pro" },
  { name: "iPhone 14 Pro Max" },
  { name: "iPhone 15" },
  { name: "iPhone 15 Plus" },
  { name: "iPhone 15 Pro" },
  { name: "iPhone 15 Pro Max" },
  { name: "iPhone 16" },
  { name: "iPhone 16 Plus" },
  { name: "iPhone 16 Pro" },
  { name: "iPhone 16 Pro Max" },
];

export default models;
